call plug#begin('~/.vim/plugged')

  " Common vim settings.
  Plug 'tpope/vim-sensible'

  " A Git plugin for Vim.
  Plug 'tpope/vim-fugitive'

  " A visual Git plugin to see what has changed in each file.
  Plug 'airblade/vim-gitgutter'

  " Syntax highlighting.
  Plug 'scrooloose/syntastic'

  " Visual plugin to show things such as the Vim mode.
  Plug 'vim-airline/vim-airline'

  " Prettier formatter.
  Plug 'prettier/vim-prettier'

  " Colorful rainbow bracket matching.
  Plug 'luochen1990/rainbow'

  " Monokai color scheme.
  Plug 'crusoexia/vim-monokai'

  " Collection of vim color schemes.
  Plug 'rafi/awesome-vim-colorschemes'

  " A color scheme based on monokai.
  Plug 'tomasr/molokai'

  " Markdown plugin.
  Plug 'plasticboy/vim-markdown'

call plug#end()

" Enable syntax highlighting.
syntax on

" Set the "pyte" color scheme.
colorscheme molokai

" Turn on line numbers.
set number

" Enable autoindent.
set autoindent

" Set backspace for certain characters.
set backspace=indent,eol,start

" Set textwidth to be 72 and visual ruler to be +1 from that.
set textwidth=72
set cc=+1

set tabstop=2
set shiftwidth=2

" Show whitespace chars.
set list
set listchars=eol:$,tab:>-,trail:~
